services:
  ui:
    build:
      context: .
      dockerfile: ./ui/Dockerfile
    ports:
      - "1234:1234"
    volumes:
      - ./ui:/app
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: sh -c "yarn install && yarn dev"

volumes:
  app_volume:
    driver: local
