/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogWildcardRouteImport } from './routes/blog/wildcard'
import { Route as BlogWhenToUseUseCallbackUseMemoRouteImport } from './routes/blog/when-to-use-useCallback-useMemo'
import { Route as BlogTunerPt3RouteImport } from './routes/blog/tuner-pt3'
import { Route as BlogTunerPt2RouteImport } from './routes/blog/tuner-pt2'
import { Route as BlogTunerPt1RouteImport } from './routes/blog/tuner-pt1'
import { Route as BlogSoundsliceRouteImport } from './routes/blog/soundslice'
import { Route as BlogSeekubeRewindRouteImport } from './routes/blog/seekube-rewind'
import { Route as BlogLangageGuerreMondeProfessionnelRouteImport } from './routes/blog/langage-guerre-monde-professionnel'
import { Route as BlogGpxFilesRouteImport } from './routes/blog/gpx-files'
import { Route as BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport } from './routes/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
import { Route as BlogDigitalPresenceOfGovernementsRouteImport } from './routes/blog/digital-presence-of-governements'
import { Route as BlogDigitalAdsRouteImport } from './routes/blog/digital-ads'
import { Route as AdminMeRouteImport } from './routes/admin/me'
import { Route as ProjectsMttsRouteRouteImport } from './routes/projects/mtts/route'
import { Route as ProjectsMttsIndexRouteImport } from './routes/projects/mtts/index'
import { Route as ProjectsCorsicaIndexRouteImport } from './routes/projects/corsica/index'
import { Route as ProjectsCoolerIndexRouteImport } from './routes/projects/cooler/index'
import { Route as ProjectsMttsScaleBuilderRouteImport } from './routes/projects/mtts/scale-builder'
import { Route as ProjectsMttsMetronomeRouteImport } from './routes/projects/mtts/metronome'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWildcardRoute = BlogWildcardRouteImport.update({
  id: '/blog/wildcard',
  path: '/blog/wildcard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhenToUseUseCallbackUseMemoRoute =
  BlogWhenToUseUseCallbackUseMemoRouteImport.update({
    id: '/blog/when-to-use-useCallback-useMemo',
    path: '/blog/when-to-use-useCallback-useMemo',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTunerPt3Route = BlogTunerPt3RouteImport.update({
  id: '/blog/tuner-pt3',
  path: '/blog/tuner-pt3',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTunerPt2Route = BlogTunerPt2RouteImport.update({
  id: '/blog/tuner-pt2',
  path: '/blog/tuner-pt2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTunerPt1Route = BlogTunerPt1RouteImport.update({
  id: '/blog/tuner-pt1',
  path: '/blog/tuner-pt1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSoundsliceRoute = BlogSoundsliceRouteImport.update({
  id: '/blog/soundslice',
  path: '/blog/soundslice',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSeekubeRewindRoute = BlogSeekubeRewindRouteImport.update({
  id: '/blog/seekube-rewind',
  path: '/blog/seekube-rewind',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLangageGuerreMondeProfessionnelRoute =
  BlogLangageGuerreMondeProfessionnelRouteImport.update({
    id: '/blog/langage-guerre-monde-professionnel',
    path: '/blog/langage-guerre-monde-professionnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGpxFilesRoute = BlogGpxFilesRouteImport.update({
  id: '/blog/gpx-files',
  path: '/blog/gpx-files',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute =
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport.update({
    id: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    path: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDigitalPresenceOfGovernementsRoute =
  BlogDigitalPresenceOfGovernementsRouteImport.update({
    id: '/blog/digital-presence-of-governements',
    path: '/blog/digital-presence-of-governements',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDigitalAdsRoute = BlogDigitalAdsRouteImport.update({
  id: '/blog/digital-ads',
  path: '/blog/digital-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeRoute = AdminMeRouteImport.update({
  id: '/admin/me',
  path: '/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMttsRouteRoute = ProjectsMttsRouteRouteImport.update({
  id: '/projects/mtts',
  path: '/projects/mtts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMttsIndexRoute = ProjectsMttsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsMttsRouteRoute,
} as any)
const ProjectsCorsicaIndexRoute = ProjectsCorsicaIndexRouteImport.update({
  id: '/projects/corsica/',
  path: '/projects/corsica/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCoolerIndexRoute = ProjectsCoolerIndexRouteImport.update({
  id: '/projects/cooler/',
  path: '/projects/cooler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsMttsScaleBuilderRoute =
  ProjectsMttsScaleBuilderRouteImport.update({
    id: '/scale-builder',
    path: '/scale-builder',
    getParentRoute: () => ProjectsMttsRouteRoute,
  } as any)
const ProjectsMttsMetronomeRoute = ProjectsMttsMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => ProjectsMttsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/projects/mtts': typeof ProjectsMttsRouteRouteWithChildren
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler': typeof ProjectsCoolerIndexRoute
  '/projects/corsica': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts/': typeof ProjectsMttsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler': typeof ProjectsCoolerIndexRoute
  '/projects/corsica': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts': typeof ProjectsMttsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/projects/mtts': typeof ProjectsMttsRouteRouteWithChildren
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler/': typeof ProjectsCoolerIndexRoute
  '/projects/corsica/': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts/': typeof ProjectsMttsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/resume'
    | '/projects/mtts'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler'
    | '/projects/corsica'
    | '/projects/mtts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler'
    | '/projects/corsica'
    | '/projects/mtts'
  id:
    | '__root__'
    | '/'
    | '/resume'
    | '/projects/mtts'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin/'
    | '/blog/'
    | '/projects/'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler/'
    | '/projects/corsica/'
    | '/projects/mtts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ResumeRoute: typeof ResumeRoute
  ProjectsMttsRouteRoute: typeof ProjectsMttsRouteRouteWithChildren
  AdminMeRoute: typeof AdminMeRoute
  BlogDigitalAdsRoute: typeof BlogDigitalAdsRoute
  BlogDigitalPresenceOfGovernementsRoute: typeof BlogDigitalPresenceOfGovernementsRoute
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  BlogGpxFilesRoute: typeof BlogGpxFilesRoute
  BlogLangageGuerreMondeProfessionnelRoute: typeof BlogLangageGuerreMondeProfessionnelRoute
  BlogSeekubeRewindRoute: typeof BlogSeekubeRewindRoute
  BlogSoundsliceRoute: typeof BlogSoundsliceRoute
  BlogTunerPt1Route: typeof BlogTunerPt1Route
  BlogTunerPt2Route: typeof BlogTunerPt2Route
  BlogTunerPt3Route: typeof BlogTunerPt3Route
  BlogWhenToUseUseCallbackUseMemoRoute: typeof BlogWhenToUseUseCallbackUseMemoRoute
  BlogWildcardRoute: typeof BlogWildcardRoute
  AdminIndexRoute: typeof AdminIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsCoolerIndexRoute: typeof ProjectsCoolerIndexRoute
  ProjectsCorsicaIndexRoute: typeof ProjectsCorsicaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wildcard': {
      id: '/blog/wildcard'
      path: '/blog/wildcard'
      fullPath: '/blog/wildcard'
      preLoaderRoute: typeof BlogWildcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/when-to-use-useCallback-useMemo': {
      id: '/blog/when-to-use-useCallback-useMemo'
      path: '/blog/when-to-use-useCallback-useMemo'
      fullPath: '/blog/when-to-use-useCallback-useMemo'
      preLoaderRoute: typeof BlogWhenToUseUseCallbackUseMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt3': {
      id: '/blog/tuner-pt3'
      path: '/blog/tuner-pt3'
      fullPath: '/blog/tuner-pt3'
      preLoaderRoute: typeof BlogTunerPt3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt2': {
      id: '/blog/tuner-pt2'
      path: '/blog/tuner-pt2'
      fullPath: '/blog/tuner-pt2'
      preLoaderRoute: typeof BlogTunerPt2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt1': {
      id: '/blog/tuner-pt1'
      path: '/blog/tuner-pt1'
      fullPath: '/blog/tuner-pt1'
      preLoaderRoute: typeof BlogTunerPt1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/soundslice': {
      id: '/blog/soundslice'
      path: '/blog/soundslice'
      fullPath: '/blog/soundslice'
      preLoaderRoute: typeof BlogSoundsliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/seekube-rewind': {
      id: '/blog/seekube-rewind'
      path: '/blog/seekube-rewind'
      fullPath: '/blog/seekube-rewind'
      preLoaderRoute: typeof BlogSeekubeRewindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/langage-guerre-monde-professionnel': {
      id: '/blog/langage-guerre-monde-professionnel'
      path: '/blog/langage-guerre-monde-professionnel'
      fullPath: '/blog/langage-guerre-monde-professionnel'
      preLoaderRoute: typeof BlogLangageGuerreMondeProfessionnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gpx-files': {
      id: '/blog/gpx-files'
      path: '/blog/gpx-files'
      fullPath: '/blog/gpx-files'
      preLoaderRoute: typeof BlogGpxFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': {
      id: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      path: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      fullPath: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      preLoaderRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/digital-presence-of-governements': {
      id: '/blog/digital-presence-of-governements'
      path: '/blog/digital-presence-of-governements'
      fullPath: '/blog/digital-presence-of-governements'
      preLoaderRoute: typeof BlogDigitalPresenceOfGovernementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/digital-ads': {
      id: '/blog/digital-ads'
      path: '/blog/digital-ads'
      fullPath: '/blog/digital-ads'
      preLoaderRoute: typeof BlogDigitalAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/me': {
      id: '/admin/me'
      path: '/admin/me'
      fullPath: '/admin/me'
      preLoaderRoute: typeof AdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mtts': {
      id: '/projects/mtts'
      path: '/projects/mtts'
      fullPath: '/projects/mtts'
      preLoaderRoute: typeof ProjectsMttsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mtts/': {
      id: '/projects/mtts/'
      path: '/'
      fullPath: '/projects/mtts/'
      preLoaderRoute: typeof ProjectsMttsIndexRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
    '/projects/corsica/': {
      id: '/projects/corsica/'
      path: '/projects/corsica'
      fullPath: '/projects/corsica'
      preLoaderRoute: typeof ProjectsCorsicaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/cooler/': {
      id: '/projects/cooler/'
      path: '/projects/cooler'
      fullPath: '/projects/cooler'
      preLoaderRoute: typeof ProjectsCoolerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/mtts/scale-builder': {
      id: '/projects/mtts/scale-builder'
      path: '/scale-builder'
      fullPath: '/projects/mtts/scale-builder'
      preLoaderRoute: typeof ProjectsMttsScaleBuilderRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
    '/projects/mtts/metronome': {
      id: '/projects/mtts/metronome'
      path: '/metronome'
      fullPath: '/projects/mtts/metronome'
      preLoaderRoute: typeof ProjectsMttsMetronomeRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
  }
}

interface ProjectsMttsRouteRouteChildren {
  ProjectsMttsMetronomeRoute: typeof ProjectsMttsMetronomeRoute
  ProjectsMttsScaleBuilderRoute: typeof ProjectsMttsScaleBuilderRoute
  ProjectsMttsIndexRoute: typeof ProjectsMttsIndexRoute
}

const ProjectsMttsRouteRouteChildren: ProjectsMttsRouteRouteChildren = {
  ProjectsMttsMetronomeRoute: ProjectsMttsMetronomeRoute,
  ProjectsMttsScaleBuilderRoute: ProjectsMttsScaleBuilderRoute,
  ProjectsMttsIndexRoute: ProjectsMttsIndexRoute,
}

const ProjectsMttsRouteRouteWithChildren =
  ProjectsMttsRouteRoute._addFileChildren(ProjectsMttsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ResumeRoute: ResumeRoute,
  ProjectsMttsRouteRoute: ProjectsMttsRouteRouteWithChildren,
  AdminMeRoute: AdminMeRoute,
  BlogDigitalAdsRoute: BlogDigitalAdsRoute,
  BlogDigitalPresenceOfGovernementsRoute:
    BlogDigitalPresenceOfGovernementsRoute,
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute:
    BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute,
  BlogGpxFilesRoute: BlogGpxFilesRoute,
  BlogLangageGuerreMondeProfessionnelRoute:
    BlogLangageGuerreMondeProfessionnelRoute,
  BlogSeekubeRewindRoute: BlogSeekubeRewindRoute,
  BlogSoundsliceRoute: BlogSoundsliceRoute,
  BlogTunerPt1Route: BlogTunerPt1Route,
  BlogTunerPt2Route: BlogTunerPt2Route,
  BlogTunerPt3Route: BlogTunerPt3Route,
  BlogWhenToUseUseCallbackUseMemoRoute: BlogWhenToUseUseCallbackUseMemoRoute,
  BlogWildcardRoute: BlogWildcardRoute,
  AdminIndexRoute: AdminIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsCoolerIndexRoute: ProjectsCoolerIndexRoute,
  ProjectsCorsicaIndexRoute: ProjectsCorsicaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
