/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogWildcardRouteImport } from './routes/blog/wildcard'
import { Route as BlogWhenToUseUseCallbackUseMemoRouteImport } from './routes/blog/when-to-use-useCallback-useMemo'
import { Route as BlogTunerPt3RouteImport } from './routes/blog/tuner-pt3'
import { Route as BlogTunerPt2RouteImport } from './routes/blog/tuner-pt2'
import { Route as BlogTunerPt1RouteImport } from './routes/blog/tuner-pt1'
import { Route as BlogSoundsliceRouteImport } from './routes/blog/soundslice'
import { Route as BlogSeekubeRewindRouteImport } from './routes/blog/seekube-rewind'
import { Route as BlogLangageGuerreMondeProfessionnelRouteImport } from './routes/blog/langage-guerre-monde-professionnel'
import { Route as BlogGpxFilesRouteImport } from './routes/blog/gpx-files'
import { Route as BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport } from './routes/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
import { Route as BlogDigitalPresenceOfGovernementsRouteImport } from './routes/blog/digital-presence-of-governements'
import { Route as BlogDigitalAdsRouteImport } from './routes/blog/digital-ads'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWildcardRoute = BlogWildcardRouteImport.update({
  id: '/blog/wildcard',
  path: '/blog/wildcard',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogWhenToUseUseCallbackUseMemoRoute =
  BlogWhenToUseUseCallbackUseMemoRouteImport.update({
    id: '/blog/when-to-use-useCallback-useMemo',
    path: '/blog/when-to-use-useCallback-useMemo',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogTunerPt3Route = BlogTunerPt3RouteImport.update({
  id: '/blog/tuner-pt3',
  path: '/blog/tuner-pt3',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTunerPt2Route = BlogTunerPt2RouteImport.update({
  id: '/blog/tuner-pt2',
  path: '/blog/tuner-pt2',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogTunerPt1Route = BlogTunerPt1RouteImport.update({
  id: '/blog/tuner-pt1',
  path: '/blog/tuner-pt1',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSoundsliceRoute = BlogSoundsliceRouteImport.update({
  id: '/blog/soundslice',
  path: '/blog/soundslice',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSeekubeRewindRoute = BlogSeekubeRewindRouteImport.update({
  id: '/blog/seekube-rewind',
  path: '/blog/seekube-rewind',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogLangageGuerreMondeProfessionnelRoute =
  BlogLangageGuerreMondeProfessionnelRouteImport.update({
    id: '/blog/langage-guerre-monde-professionnel',
    path: '/blog/langage-guerre-monde-professionnel',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogGpxFilesRoute = BlogGpxFilesRouteImport.update({
  id: '/blog/gpx-files',
  path: '/blog/gpx-files',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute =
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport.update({
    id: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    path: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDigitalPresenceOfGovernementsRoute =
  BlogDigitalPresenceOfGovernementsRouteImport.update({
    id: '/blog/digital-presence-of-governements',
    path: '/blog/digital-presence-of-governements',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogDigitalAdsRoute = BlogDigitalAdsRouteImport.update({
  id: '/blog/digital-ads',
  path: '/blog/digital-ads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/resume': typeof ResumeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/resume'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/blog'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/resume'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/resume'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ResumeRoute: typeof ResumeRoute
  BlogDigitalAdsRoute: typeof BlogDigitalAdsRoute
  BlogDigitalPresenceOfGovernementsRoute: typeof BlogDigitalPresenceOfGovernementsRoute
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  BlogGpxFilesRoute: typeof BlogGpxFilesRoute
  BlogLangageGuerreMondeProfessionnelRoute: typeof BlogLangageGuerreMondeProfessionnelRoute
  BlogSeekubeRewindRoute: typeof BlogSeekubeRewindRoute
  BlogSoundsliceRoute: typeof BlogSoundsliceRoute
  BlogTunerPt1Route: typeof BlogTunerPt1Route
  BlogTunerPt2Route: typeof BlogTunerPt2Route
  BlogTunerPt3Route: typeof BlogTunerPt3Route
  BlogWhenToUseUseCallbackUseMemoRoute: typeof BlogWhenToUseUseCallbackUseMemoRoute
  BlogWildcardRoute: typeof BlogWildcardRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/wildcard': {
      id: '/blog/wildcard'
      path: '/blog/wildcard'
      fullPath: '/blog/wildcard'
      preLoaderRoute: typeof BlogWildcardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/when-to-use-useCallback-useMemo': {
      id: '/blog/when-to-use-useCallback-useMemo'
      path: '/blog/when-to-use-useCallback-useMemo'
      fullPath: '/blog/when-to-use-useCallback-useMemo'
      preLoaderRoute: typeof BlogWhenToUseUseCallbackUseMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt3': {
      id: '/blog/tuner-pt3'
      path: '/blog/tuner-pt3'
      fullPath: '/blog/tuner-pt3'
      preLoaderRoute: typeof BlogTunerPt3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt2': {
      id: '/blog/tuner-pt2'
      path: '/blog/tuner-pt2'
      fullPath: '/blog/tuner-pt2'
      preLoaderRoute: typeof BlogTunerPt2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/tuner-pt1': {
      id: '/blog/tuner-pt1'
      path: '/blog/tuner-pt1'
      fullPath: '/blog/tuner-pt1'
      preLoaderRoute: typeof BlogTunerPt1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/soundslice': {
      id: '/blog/soundslice'
      path: '/blog/soundslice'
      fullPath: '/blog/soundslice'
      preLoaderRoute: typeof BlogSoundsliceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/seekube-rewind': {
      id: '/blog/seekube-rewind'
      path: '/blog/seekube-rewind'
      fullPath: '/blog/seekube-rewind'
      preLoaderRoute: typeof BlogSeekubeRewindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/langage-guerre-monde-professionnel': {
      id: '/blog/langage-guerre-monde-professionnel'
      path: '/blog/langage-guerre-monde-professionnel'
      fullPath: '/blog/langage-guerre-monde-professionnel'
      preLoaderRoute: typeof BlogLangageGuerreMondeProfessionnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/gpx-files': {
      id: '/blog/gpx-files'
      path: '/blog/gpx-files'
      fullPath: '/blog/gpx-files'
      preLoaderRoute: typeof BlogGpxFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': {
      id: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      path: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      fullPath: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      preLoaderRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/digital-presence-of-governements': {
      id: '/blog/digital-presence-of-governements'
      path: '/blog/digital-presence-of-governements'
      fullPath: '/blog/digital-presence-of-governements'
      preLoaderRoute: typeof BlogDigitalPresenceOfGovernementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/digital-ads': {
      id: '/blog/digital-ads'
      path: '/blog/digital-ads'
      fullPath: '/blog/digital-ads'
      preLoaderRoute: typeof BlogDigitalAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ResumeRoute: ResumeRoute,
  BlogDigitalAdsRoute: BlogDigitalAdsRoute,
  BlogDigitalPresenceOfGovernementsRoute:
    BlogDigitalPresenceOfGovernementsRoute,
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute:
    BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute,
  BlogGpxFilesRoute: BlogGpxFilesRoute,
  BlogLangageGuerreMondeProfessionnelRoute:
    BlogLangageGuerreMondeProfessionnelRoute,
  BlogSeekubeRewindRoute: BlogSeekubeRewindRoute,
  BlogSoundsliceRoute: BlogSoundsliceRoute,
  BlogTunerPt1Route: BlogTunerPt1Route,
  BlogTunerPt2Route: BlogTunerPt2Route,
  BlogTunerPt3Route: BlogTunerPt3Route,
  BlogWhenToUseUseCallbackUseMemoRoute: BlogWhenToUseUseCallbackUseMemoRoute,
  BlogWildcardRoute: BlogWildcardRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
