/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogWildcardRouteImport } from './routes/blog/wildcard'
import { Route as BlogWhenToUseUseCallbackUseMemoRouteImport } from './routes/blog/when-to-use-useCallback-useMemo'
import { Route as BlogTunerPt3RouteImport } from './routes/blog/tuner-pt3'
import { Route as BlogTunerPt2RouteImport } from './routes/blog/tuner-pt2'
import { Route as BlogTunerPt1RouteImport } from './routes/blog/tuner-pt1'
import { Route as BlogSoundsliceRouteImport } from './routes/blog/soundslice'
import { Route as BlogSeekubeRewindRouteImport } from './routes/blog/seekube-rewind'
import { Route as BlogLangageGuerreMondeProfessionnelRouteImport } from './routes/blog/langage-guerre-monde-professionnel'
import { Route as BlogGpxFilesRouteImport } from './routes/blog/gpx-files'
import { Route as BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport } from './routes/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
import { Route as BlogDigitalPresenceOfGovernementsRouteImport } from './routes/blog/digital-presence-of-governements'
import { Route as BlogDigitalAdsRouteImport } from './routes/blog/digital-ads'
import { Route as AdminMeRouteImport } from './routes/admin/me'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ProjectsMttsRouteRouteImport } from './routes/projects/mtts/route'
import { Route as ProjectsCorsicaRouteRouteImport } from './routes/projects/corsica/route'
import { Route as ProjectsMttsIndexRouteImport } from './routes/projects/mtts/index'
import { Route as ProjectsCorsicaIndexRouteImport } from './routes/projects/corsica/index'
import { Route as ProjectsCoolerIndexRouteImport } from './routes/projects/cooler/index'
import { Route as ProjectsMttsScaleBuilderRouteImport } from './routes/projects/mtts/scale-builder'
import { Route as ProjectsMttsMetronomeRouteImport } from './routes/projects/mtts/metronome'
import { Route as ProjectsCorsicaMergeRouteImport } from './routes/projects/corsica/merge'
import { Route as ProjectsCorsicaAnalyseRouteRouteImport } from './routes/projects/corsica/analyse/route'
import { Route as ProjectsCorsicaAnalyseIndexRouteImport } from './routes/projects/corsica/analyse/index'
import { Route as ProjectsCoolerColorSlugIndexRouteImport } from './routes/projects/cooler/$colorSlug/index'
import { Route as ProjectsCorsicaAnalyseFileRouteImport } from './routes/projects/corsica/analyse/$file'
import { Route as ProjectsCoolerColorSlugCombinationRouteImport } from './routes/projects/cooler/$colorSlug/$combination'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogWildcardRoute = BlogWildcardRouteImport.update({
  id: '/wildcard',
  path: '/wildcard',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogWhenToUseUseCallbackUseMemoRoute =
  BlogWhenToUseUseCallbackUseMemoRouteImport.update({
    id: '/when-to-use-useCallback-useMemo',
    path: '/when-to-use-useCallback-useMemo',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogTunerPt3Route = BlogTunerPt3RouteImport.update({
  id: '/tuner-pt3',
  path: '/tuner-pt3',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogTunerPt2Route = BlogTunerPt2RouteImport.update({
  id: '/tuner-pt2',
  path: '/tuner-pt2',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogTunerPt1Route = BlogTunerPt1RouteImport.update({
  id: '/tuner-pt1',
  path: '/tuner-pt1',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSoundsliceRoute = BlogSoundsliceRouteImport.update({
  id: '/soundslice',
  path: '/soundslice',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogSeekubeRewindRoute = BlogSeekubeRewindRouteImport.update({
  id: '/seekube-rewind',
  path: '/seekube-rewind',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogLangageGuerreMondeProfessionnelRoute =
  BlogLangageGuerreMondeProfessionnelRouteImport.update({
    id: '/langage-guerre-monde-professionnel',
    path: '/langage-guerre-monde-professionnel',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogGpxFilesRoute = BlogGpxFilesRouteImport.update({
  id: '/gpx-files',
  path: '/gpx-files',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute =
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport.update({
    id: '/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    path: '/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogDigitalPresenceOfGovernementsRoute =
  BlogDigitalPresenceOfGovernementsRouteImport.update({
    id: '/digital-presence-of-governements',
    path: '/digital-presence-of-governements',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogDigitalAdsRoute = BlogDigitalAdsRouteImport.update({
  id: '/digital-ads',
  path: '/digital-ads',
  getParentRoute: () => BlogRouteRoute,
} as any)
const AdminMeRoute = AdminMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProjectsMttsRouteRoute = ProjectsMttsRouteRouteImport.update({
  id: '/mtts',
  path: '/mtts',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsCorsicaRouteRoute = ProjectsCorsicaRouteRouteImport.update({
  id: '/corsica',
  path: '/corsica',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsMttsIndexRoute = ProjectsMttsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsMttsRouteRoute,
} as any)
const ProjectsCorsicaIndexRoute = ProjectsCorsicaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsCorsicaRouteRoute,
} as any)
const ProjectsCoolerIndexRoute = ProjectsCoolerIndexRouteImport.update({
  id: '/cooler/',
  path: '/cooler/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const ProjectsMttsScaleBuilderRoute =
  ProjectsMttsScaleBuilderRouteImport.update({
    id: '/scale-builder',
    path: '/scale-builder',
    getParentRoute: () => ProjectsMttsRouteRoute,
  } as any)
const ProjectsMttsMetronomeRoute = ProjectsMttsMetronomeRouteImport.update({
  id: '/metronome',
  path: '/metronome',
  getParentRoute: () => ProjectsMttsRouteRoute,
} as any)
const ProjectsCorsicaMergeRoute = ProjectsCorsicaMergeRouteImport.update({
  id: '/merge',
  path: '/merge',
  getParentRoute: () => ProjectsCorsicaRouteRoute,
} as any)
const ProjectsCorsicaAnalyseRouteRoute =
  ProjectsCorsicaAnalyseRouteRouteImport.update({
    id: '/analyse',
    path: '/analyse',
    getParentRoute: () => ProjectsCorsicaRouteRoute,
  } as any)
const ProjectsCorsicaAnalyseIndexRoute =
  ProjectsCorsicaAnalyseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsCorsicaAnalyseRouteRoute,
  } as any)
const ProjectsCoolerColorSlugIndexRoute =
  ProjectsCoolerColorSlugIndexRouteImport.update({
    id: '/cooler/$colorSlug/',
    path: '/cooler/$colorSlug/',
    getParentRoute: () => ProjectsRouteRoute,
  } as any)
const ProjectsCorsicaAnalyseFileRoute =
  ProjectsCorsicaAnalyseFileRouteImport.update({
    id: '/$file',
    path: '/$file',
    getParentRoute: () => ProjectsCorsicaAnalyseRouteRoute,
  } as any)
const ProjectsCoolerColorSlugCombinationRoute =
  ProjectsCoolerColorSlugCombinationRouteImport.update({
    id: '/cooler/$colorSlug/$combination',
    path: '/cooler/$colorSlug/$combination',
    getParentRoute: () => ProjectsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/projects/corsica': typeof ProjectsCorsicaRouteRouteWithChildren
  '/projects/mtts': typeof ProjectsMttsRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/corsica/analyse': typeof ProjectsCorsicaAnalyseRouteRouteWithChildren
  '/projects/corsica/merge': typeof ProjectsCorsicaMergeRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler': typeof ProjectsCoolerIndexRoute
  '/projects/corsica/': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts/': typeof ProjectsMttsIndexRoute
  '/projects/cooler/$colorSlug/$combination': typeof ProjectsCoolerColorSlugCombinationRoute
  '/projects/corsica/analyse/$file': typeof ProjectsCorsicaAnalyseFileRoute
  '/projects/cooler/$colorSlug': typeof ProjectsCoolerColorSlugIndexRoute
  '/projects/corsica/analyse/': typeof ProjectsCorsicaAnalyseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/resume': typeof ResumeRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/corsica/merge': typeof ProjectsCorsicaMergeRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler': typeof ProjectsCoolerIndexRoute
  '/projects/corsica': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts': typeof ProjectsMttsIndexRoute
  '/projects/cooler/$colorSlug/$combination': typeof ProjectsCoolerColorSlugCombinationRoute
  '/projects/corsica/analyse/$file': typeof ProjectsCorsicaAnalyseFileRoute
  '/projects/cooler/$colorSlug': typeof ProjectsCoolerColorSlugIndexRoute
  '/projects/corsica/analyse': typeof ProjectsCorsicaAnalyseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/blog': typeof BlogRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/resume': typeof ResumeRoute
  '/projects/corsica': typeof ProjectsCorsicaRouteRouteWithChildren
  '/projects/mtts': typeof ProjectsMttsRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/me': typeof AdminMeRoute
  '/blog/digital-ads': typeof BlogDigitalAdsRoute
  '/blog/digital-presence-of-governements': typeof BlogDigitalPresenceOfGovernementsRoute
  '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  '/blog/gpx-files': typeof BlogGpxFilesRoute
  '/blog/langage-guerre-monde-professionnel': typeof BlogLangageGuerreMondeProfessionnelRoute
  '/blog/seekube-rewind': typeof BlogSeekubeRewindRoute
  '/blog/soundslice': typeof BlogSoundsliceRoute
  '/blog/tuner-pt1': typeof BlogTunerPt1Route
  '/blog/tuner-pt2': typeof BlogTunerPt2Route
  '/blog/tuner-pt3': typeof BlogTunerPt3Route
  '/blog/when-to-use-useCallback-useMemo': typeof BlogWhenToUseUseCallbackUseMemoRoute
  '/blog/wildcard': typeof BlogWildcardRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/projects/corsica/analyse': typeof ProjectsCorsicaAnalyseRouteRouteWithChildren
  '/projects/corsica/merge': typeof ProjectsCorsicaMergeRoute
  '/projects/mtts/metronome': typeof ProjectsMttsMetronomeRoute
  '/projects/mtts/scale-builder': typeof ProjectsMttsScaleBuilderRoute
  '/projects/cooler/': typeof ProjectsCoolerIndexRoute
  '/projects/corsica/': typeof ProjectsCorsicaIndexRoute
  '/projects/mtts/': typeof ProjectsMttsIndexRoute
  '/projects/cooler/$colorSlug/$combination': typeof ProjectsCoolerColorSlugCombinationRoute
  '/projects/corsica/analyse/$file': typeof ProjectsCorsicaAnalyseFileRoute
  '/projects/cooler/$colorSlug/': typeof ProjectsCoolerColorSlugIndexRoute
  '/projects/corsica/analyse/': typeof ProjectsCorsicaAnalyseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/projects/corsica'
    | '/projects/mtts'
    | '/admin/login'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin/'
    | '/blog/'
    | '/projects/'
    | '/projects/corsica/analyse'
    | '/projects/corsica/merge'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler'
    | '/projects/corsica/'
    | '/projects/mtts/'
    | '/projects/cooler/$colorSlug/$combination'
    | '/projects/corsica/analyse/$file'
    | '/projects/cooler/$colorSlug'
    | '/projects/corsica/analyse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/resume'
    | '/admin/login'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/projects/corsica/merge'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler'
    | '/projects/corsica'
    | '/projects/mtts'
    | '/projects/cooler/$colorSlug/$combination'
    | '/projects/corsica/analyse/$file'
    | '/projects/cooler/$colorSlug'
    | '/projects/corsica/analyse'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/projects'
    | '/resume'
    | '/projects/corsica'
    | '/projects/mtts'
    | '/admin/login'
    | '/admin/me'
    | '/blog/digital-ads'
    | '/blog/digital-presence-of-governements'
    | '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
    | '/blog/gpx-files'
    | '/blog/langage-guerre-monde-professionnel'
    | '/blog/seekube-rewind'
    | '/blog/soundslice'
    | '/blog/tuner-pt1'
    | '/blog/tuner-pt2'
    | '/blog/tuner-pt3'
    | '/blog/when-to-use-useCallback-useMemo'
    | '/blog/wildcard'
    | '/admin/'
    | '/blog/'
    | '/projects/'
    | '/projects/corsica/analyse'
    | '/projects/corsica/merge'
    | '/projects/mtts/metronome'
    | '/projects/mtts/scale-builder'
    | '/projects/cooler/'
    | '/projects/corsica/'
    | '/projects/mtts/'
    | '/projects/cooler/$colorSlug/$combination'
    | '/projects/corsica/analyse/$file'
    | '/projects/cooler/$colorSlug/'
    | '/projects/corsica/analyse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  ResumeRoute: typeof ResumeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/wildcard': {
      id: '/blog/wildcard'
      path: '/wildcard'
      fullPath: '/blog/wildcard'
      preLoaderRoute: typeof BlogWildcardRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/when-to-use-useCallback-useMemo': {
      id: '/blog/when-to-use-useCallback-useMemo'
      path: '/when-to-use-useCallback-useMemo'
      fullPath: '/blog/when-to-use-useCallback-useMemo'
      preLoaderRoute: typeof BlogWhenToUseUseCallbackUseMemoRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/tuner-pt3': {
      id: '/blog/tuner-pt3'
      path: '/tuner-pt3'
      fullPath: '/blog/tuner-pt3'
      preLoaderRoute: typeof BlogTunerPt3RouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/tuner-pt2': {
      id: '/blog/tuner-pt2'
      path: '/tuner-pt2'
      fullPath: '/blog/tuner-pt2'
      preLoaderRoute: typeof BlogTunerPt2RouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/tuner-pt1': {
      id: '/blog/tuner-pt1'
      path: '/tuner-pt1'
      fullPath: '/blog/tuner-pt1'
      preLoaderRoute: typeof BlogTunerPt1RouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/soundslice': {
      id: '/blog/soundslice'
      path: '/soundslice'
      fullPath: '/blog/soundslice'
      preLoaderRoute: typeof BlogSoundsliceRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/seekube-rewind': {
      id: '/blog/seekube-rewind'
      path: '/seekube-rewind'
      fullPath: '/blog/seekube-rewind'
      preLoaderRoute: typeof BlogSeekubeRewindRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/langage-guerre-monde-professionnel': {
      id: '/blog/langage-guerre-monde-professionnel'
      path: '/langage-guerre-monde-professionnel'
      fullPath: '/blog/langage-guerre-monde-professionnel'
      preLoaderRoute: typeof BlogLangageGuerreMondeProfessionnelRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/gpx-files': {
      id: '/blog/gpx-files'
      path: '/gpx-files'
      fullPath: '/blog/gpx-files'
      preLoaderRoute: typeof BlogGpxFilesRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe': {
      id: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      path: '/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      fullPath: '/blog/en-tant-qu-ingenieur-quel-est-mon-role-dans-la-societe'
      preLoaderRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/digital-presence-of-governements': {
      id: '/blog/digital-presence-of-governements'
      path: '/digital-presence-of-governements'
      fullPath: '/blog/digital-presence-of-governements'
      preLoaderRoute: typeof BlogDigitalPresenceOfGovernementsRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/digital-ads': {
      id: '/blog/digital-ads'
      path: '/digital-ads'
      fullPath: '/blog/digital-ads'
      preLoaderRoute: typeof BlogDigitalAdsRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/admin/me': {
      id: '/admin/me'
      path: '/me'
      fullPath: '/admin/me'
      preLoaderRoute: typeof AdminMeRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/projects/mtts': {
      id: '/projects/mtts'
      path: '/mtts'
      fullPath: '/projects/mtts'
      preLoaderRoute: typeof ProjectsMttsRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/corsica': {
      id: '/projects/corsica'
      path: '/corsica'
      fullPath: '/projects/corsica'
      preLoaderRoute: typeof ProjectsCorsicaRouteRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/mtts/': {
      id: '/projects/mtts/'
      path: '/'
      fullPath: '/projects/mtts/'
      preLoaderRoute: typeof ProjectsMttsIndexRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
    '/projects/corsica/': {
      id: '/projects/corsica/'
      path: '/'
      fullPath: '/projects/corsica/'
      preLoaderRoute: typeof ProjectsCorsicaIndexRouteImport
      parentRoute: typeof ProjectsCorsicaRouteRoute
    }
    '/projects/cooler/': {
      id: '/projects/cooler/'
      path: '/cooler'
      fullPath: '/projects/cooler'
      preLoaderRoute: typeof ProjectsCoolerIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/mtts/scale-builder': {
      id: '/projects/mtts/scale-builder'
      path: '/scale-builder'
      fullPath: '/projects/mtts/scale-builder'
      preLoaderRoute: typeof ProjectsMttsScaleBuilderRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
    '/projects/mtts/metronome': {
      id: '/projects/mtts/metronome'
      path: '/metronome'
      fullPath: '/projects/mtts/metronome'
      preLoaderRoute: typeof ProjectsMttsMetronomeRouteImport
      parentRoute: typeof ProjectsMttsRouteRoute
    }
    '/projects/corsica/merge': {
      id: '/projects/corsica/merge'
      path: '/merge'
      fullPath: '/projects/corsica/merge'
      preLoaderRoute: typeof ProjectsCorsicaMergeRouteImport
      parentRoute: typeof ProjectsCorsicaRouteRoute
    }
    '/projects/corsica/analyse': {
      id: '/projects/corsica/analyse'
      path: '/analyse'
      fullPath: '/projects/corsica/analyse'
      preLoaderRoute: typeof ProjectsCorsicaAnalyseRouteRouteImport
      parentRoute: typeof ProjectsCorsicaRouteRoute
    }
    '/projects/corsica/analyse/': {
      id: '/projects/corsica/analyse/'
      path: '/'
      fullPath: '/projects/corsica/analyse/'
      preLoaderRoute: typeof ProjectsCorsicaAnalyseIndexRouteImport
      parentRoute: typeof ProjectsCorsicaAnalyseRouteRoute
    }
    '/projects/cooler/$colorSlug/': {
      id: '/projects/cooler/$colorSlug/'
      path: '/cooler/$colorSlug'
      fullPath: '/projects/cooler/$colorSlug'
      preLoaderRoute: typeof ProjectsCoolerColorSlugIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/projects/corsica/analyse/$file': {
      id: '/projects/corsica/analyse/$file'
      path: '/$file'
      fullPath: '/projects/corsica/analyse/$file'
      preLoaderRoute: typeof ProjectsCorsicaAnalyseFileRouteImport
      parentRoute: typeof ProjectsCorsicaAnalyseRouteRoute
    }
    '/projects/cooler/$colorSlug/$combination': {
      id: '/projects/cooler/$colorSlug/$combination'
      path: '/cooler/$colorSlug/$combination'
      fullPath: '/projects/cooler/$colorSlug/$combination'
      preLoaderRoute: typeof ProjectsCoolerColorSlugCombinationRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMeRoute: typeof AdminMeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminMeRoute: AdminMeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface BlogRouteRouteChildren {
  BlogDigitalAdsRoute: typeof BlogDigitalAdsRoute
  BlogDigitalPresenceOfGovernementsRoute: typeof BlogDigitalPresenceOfGovernementsRoute
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute: typeof BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute
  BlogGpxFilesRoute: typeof BlogGpxFilesRoute
  BlogLangageGuerreMondeProfessionnelRoute: typeof BlogLangageGuerreMondeProfessionnelRoute
  BlogSeekubeRewindRoute: typeof BlogSeekubeRewindRoute
  BlogSoundsliceRoute: typeof BlogSoundsliceRoute
  BlogTunerPt1Route: typeof BlogTunerPt1Route
  BlogTunerPt2Route: typeof BlogTunerPt2Route
  BlogTunerPt3Route: typeof BlogTunerPt3Route
  BlogWhenToUseUseCallbackUseMemoRoute: typeof BlogWhenToUseUseCallbackUseMemoRoute
  BlogWildcardRoute: typeof BlogWildcardRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  BlogDigitalAdsRoute: BlogDigitalAdsRoute,
  BlogDigitalPresenceOfGovernementsRoute:
    BlogDigitalPresenceOfGovernementsRoute,
  BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute:
    BlogEnTantQuIngenieurQuelEstMonRoleDansLaSocieteRoute,
  BlogGpxFilesRoute: BlogGpxFilesRoute,
  BlogLangageGuerreMondeProfessionnelRoute:
    BlogLangageGuerreMondeProfessionnelRoute,
  BlogSeekubeRewindRoute: BlogSeekubeRewindRoute,
  BlogSoundsliceRoute: BlogSoundsliceRoute,
  BlogTunerPt1Route: BlogTunerPt1Route,
  BlogTunerPt2Route: BlogTunerPt2Route,
  BlogTunerPt3Route: BlogTunerPt3Route,
  BlogWhenToUseUseCallbackUseMemoRoute: BlogWhenToUseUseCallbackUseMemoRoute,
  BlogWildcardRoute: BlogWildcardRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface ProjectsCorsicaAnalyseRouteRouteChildren {
  ProjectsCorsicaAnalyseFileRoute: typeof ProjectsCorsicaAnalyseFileRoute
  ProjectsCorsicaAnalyseIndexRoute: typeof ProjectsCorsicaAnalyseIndexRoute
}

const ProjectsCorsicaAnalyseRouteRouteChildren: ProjectsCorsicaAnalyseRouteRouteChildren =
  {
    ProjectsCorsicaAnalyseFileRoute: ProjectsCorsicaAnalyseFileRoute,
    ProjectsCorsicaAnalyseIndexRoute: ProjectsCorsicaAnalyseIndexRoute,
  }

const ProjectsCorsicaAnalyseRouteRouteWithChildren =
  ProjectsCorsicaAnalyseRouteRoute._addFileChildren(
    ProjectsCorsicaAnalyseRouteRouteChildren,
  )

interface ProjectsCorsicaRouteRouteChildren {
  ProjectsCorsicaAnalyseRouteRoute: typeof ProjectsCorsicaAnalyseRouteRouteWithChildren
  ProjectsCorsicaMergeRoute: typeof ProjectsCorsicaMergeRoute
  ProjectsCorsicaIndexRoute: typeof ProjectsCorsicaIndexRoute
}

const ProjectsCorsicaRouteRouteChildren: ProjectsCorsicaRouteRouteChildren = {
  ProjectsCorsicaAnalyseRouteRoute:
    ProjectsCorsicaAnalyseRouteRouteWithChildren,
  ProjectsCorsicaMergeRoute: ProjectsCorsicaMergeRoute,
  ProjectsCorsicaIndexRoute: ProjectsCorsicaIndexRoute,
}

const ProjectsCorsicaRouteRouteWithChildren =
  ProjectsCorsicaRouteRoute._addFileChildren(ProjectsCorsicaRouteRouteChildren)

interface ProjectsMttsRouteRouteChildren {
  ProjectsMttsMetronomeRoute: typeof ProjectsMttsMetronomeRoute
  ProjectsMttsScaleBuilderRoute: typeof ProjectsMttsScaleBuilderRoute
  ProjectsMttsIndexRoute: typeof ProjectsMttsIndexRoute
}

const ProjectsMttsRouteRouteChildren: ProjectsMttsRouteRouteChildren = {
  ProjectsMttsMetronomeRoute: ProjectsMttsMetronomeRoute,
  ProjectsMttsScaleBuilderRoute: ProjectsMttsScaleBuilderRoute,
  ProjectsMttsIndexRoute: ProjectsMttsIndexRoute,
}

const ProjectsMttsRouteRouteWithChildren =
  ProjectsMttsRouteRoute._addFileChildren(ProjectsMttsRouteRouteChildren)

interface ProjectsRouteRouteChildren {
  ProjectsCorsicaRouteRoute: typeof ProjectsCorsicaRouteRouteWithChildren
  ProjectsMttsRouteRoute: typeof ProjectsMttsRouteRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ProjectsCoolerIndexRoute: typeof ProjectsCoolerIndexRoute
  ProjectsCoolerColorSlugCombinationRoute: typeof ProjectsCoolerColorSlugCombinationRoute
  ProjectsCoolerColorSlugIndexRoute: typeof ProjectsCoolerColorSlugIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsCorsicaRouteRoute: ProjectsCorsicaRouteRouteWithChildren,
  ProjectsMttsRouteRoute: ProjectsMttsRouteRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ProjectsCoolerIndexRoute: ProjectsCoolerIndexRoute,
  ProjectsCoolerColorSlugCombinationRoute:
    ProjectsCoolerColorSlugCombinationRoute,
  ProjectsCoolerColorSlugIndexRoute: ProjectsCoolerColorSlugIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  ResumeRoute: ResumeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
