"""Added relation between user and song

Revision ID: 08040b908907
Revises: 0f0e03beb336
Create Date: 2025-11-05 14:38:16.172994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08040b908907'
down_revision: Union[str, Sequence[str], None] = '0f0e03beb336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('user_id', sa.String, nullable=False))
    op.create_foreign_key('fk_song_user', 'song', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_song_user', 'song', type_='foreignkey')
    op.drop_column('song', 'user_id')
    # ### end Alembic commands ###
