- name: Install fail2ban packages
  apt:
    name: ["fail2ban"]
  when: ansible_facts['distribution_major_version'] != '24'

# Workaround waiting fail2ban fix for Ubuntu 24.04
# https://github.com/fail2ban/fail2ban/issues/3487
# https://bugs.launchpad.net/ubuntu/+source/fail2ban/+bug/2055114
- name: Install fail2ban packages for Ubuntu 24.04
  apt:
    deb: https://launchpad.net/ubuntu/+source/fail2ban/1.1.0-1/+build/28291332/+files/fail2ban_1.1.0-1_all.deb
  when: ansible_facts['distribution_major_version'] == '24'

- name: start-fail2ban
  service:
    name: fail2ban
    enabled: true
    state: started

- name: Ensure nginx error.log exists
  ansible.builtin.shell: touch /opt/app/system/nginx/error.log

- name: Copy fail2ban actions
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/action.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/setup/fail2ban/action.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban filters
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/filter.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/setup/fail2ban/filter.d/*"
  notify: restart-fail2ban

- name: Copy fail2ban jails
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/fail2ban/jail.d"
    owner: "root"
    mode: 0600
  with_fileglob:
    - "{{playbook_dir}}/../files/setup/fail2ban/jail.d/*"
  notify: restart-fail2ban
