- name: Mise à jour des packages
  apt:
    name: "*"
    state: latest
    update_cache: yes

- name: Remove unused package
  apt:
    name: ["tcpdump", "gdb", "libX11", "telnet", "gcc", "ftp"]
    state: absent

- include_role:
    name: geerlingguy.docker
  vars:
    docker_daemon_options:
      dns: ["172.17.0.1"]

- include_role:
    name: geerlingguy.docker
  vars:
    docker_daemon_options:
      log-driver: local
      dns: ["172.17.0.1"]

- name: Docker login
  shell: "echo $PASS | docker login ghcr.io -u '{{ vault.infra.DOCKER.user }}' --password-stdin"
  environment:
    PASS: "{{ vault.infra.DOCKER.token }}"

- name: Vérification binaires ctop déja installés
  stat: path=/usr/local/bin/ctop
  register: ctop

- name: Installation ctop
  when: ctop.stat.exists == False
  shell: "wget https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64 -O /usr/local/bin/ctop && chmod +x /usr/local/bin/ctop"

- name: Installation des packages apt
  apt:
    name: ["vim", "htop", "jq", "git", "python3-pip", "python3-docker"]

- name: Set timezone to Europe/Paris
  community.general.timezone:
    name: Europe/Paris

- name: Definition clavier francais
  lineinfile:
    path: /etc/default/keyboard
    regexp: '^XKBLAYOUT=\"\w*\"$'
    line: 'XKBLAYOUT="fr"'

- name: Définition de l'environnement
  copy:
    dest: /env
    content: "{{env_type}}"

#See https://unix.stackexchange.com/questions/186859/understand-hostname-and-etc-hosts
- name: Définition du nom de l'hôte
  hostname:
    name: "{{ host_name }}"

#Works only with OVH instance
- name: Ajout de l'hôte en tant qu'alias dans /etc/hosts
  lineinfile:
    dest: /etc/hosts
    backup: true
    backrefs: true
    state: present
    regexp: '^(127\.0\.1\.1\tvps-[a-z0-9]+.vps.ovh.net(?:\.novalocal)?\tvps-[a-z0-9]+)( {{host_name}})?$'
    line: '\1 {{ host_name }}'

- name: Configuration de ulimit open files
  community.general.pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: "nofile"
    value: "64000"

- name: Configuration de ulimit processes
  community.general.pam_limits:
    domain: "*"
    limit_type: "-"
    limit_item: "nproc"
    value: "64000"
