- name: Ensure group "website" exists
  group:
    name: website
    state: present

- include_tasks: _create-sudoers.yml
  loop: "{{habilitations}}"
  loop_control:
    loop_var: habilitation

- name: "Création utilisateur deploy"
  user:
    name: "{{ vault.infra.TECHNICAL_USER.USERNAME }}"
    password: "{{ vault.infra.TECHNICAL_USER.PASSWORD_HASH }}"
    update_password: always
    shell: /bin/bash
    groups: sudo,website
    append: yes
    password_expire_max: 90
    password_expire_min: 1

- name: Ensure .bash_logout file exists and has the required content for deploy user
  copy:
    src: "{{playbook_dir}}/../files/setup/homedir/bash_logout"
    dest: /home/deploy/.bash_logout
    owner: deploy
    group: deploy
    mode: "0644"

- name: Ensure .bash_logout file exists and has the required content for root user
  copy:
    src: "{{playbook_dir}}/../files/setup/homedir/bash_logout"
    dest: /root/.bash_logout
    owner: root
    group: root
    mode: "0644"

- name: "Ajout des clés d'autorisation à l'utilisateur deploy"
  authorized_key:
    user: "deploy"
    state: present
    key: "{{ vault.infra.TECHNICAL_USER.PUBLIC_KEY }}"

- name: "Ajout de la SSH private key"
  copy:
    dest: "~/.ssh/id_ed25519"
    content: "{{ vault.infra.TECHNICAL_USER.PRIVATE_KEY }}"
    owner: root
    mode: "700"

- name: "Ajout de la SSH key"
  shell: |
    eval "$(ssh-agent)"
    ssh-add ~/.ssh/id_ed25519
