import type { ClientPathsWithMethod,MethodResponse } from "openapi-fetch";
import createClient, { wrapAsPathBasedClient } from "openapi-fetch";

import { getClientConfig, getServerConfig, isServer } from "@/lib/config";

import type { paths } from "./types/api"; // generated by openapi-typescript

export const ApiClient = createClient<paths>({
  baseUrl: isServer
    ? getServerConfig().serverUrl
    : getClientConfig().serverUrl
  });

export const PathBasedApiClient = wrapAsPathBasedClient(ApiClient);

export type Response<
  Method extends  "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace",
  Path extends ClientPathsWithMethod<typeof ApiClient, Method>
>  = MethodResponse<typeof ApiClient, Method, Path>