import Cookies from 'js-cookie';
import type { ClientPathsWithMethod,MethodResponse, Middleware } from "openapi-fetch";
import createClient, { wrapAsPathBasedClient } from "openapi-fetch";

import { ACCESS_TOKEN_COOKIE_KEY } from "@/const";
import { getClientConfig, getServerConfig, isServer } from "@/lib/config";

import type { paths } from "./types/api"; // generated by openapi-typescript

const ApiClient = createClient<paths>({
  baseUrl: isServer
    ? getServerConfig().serverUrl
    : getClientConfig().serverUrl,
  });

const authMiddleware: Middleware = {
  async onRequest({ request, options }) {
    if (!isServer) {
      const token = Cookies.get(ACCESS_TOKEN_COOKIE_KEY);
      if (token) {
        request.headers.set("Authorization", `Bearer ${token}`);
      }
    }
    return request;
  },
};

ApiClient.use(authMiddleware);

export { ApiClient };

export const PathBasedApiClient = wrapAsPathBasedClient(ApiClient);

export type Response<
  Method extends  "get" | "put" | "post" | "delete" | "options" | "head" | "patch" | "trace",
  Path extends ClientPathsWithMethod<typeof ApiClient, Method>
>  = MethodResponse<typeof ApiClient, Method, Path>